### ISSUE TITLE
Homematic constant disconnects hmip rfusb

### ISSUE THREAD

**Issue by biejay** [home-assistant/hassio-addons#1008]
I managed to pair **two thermostats (HmIP-eTRV-B and HmIP-eTRV-2)** and **one window sensor (HmIP-SWDM)** to my hassio. 
Setup: [HmIP RFUSB](https://de.elv.com/elv-homematic-ip-arr-bausatz-rf-usb-stick-fuer-alternative-steuerungsplattformen-hmip-rfusb-fuer-smart-home-hausautomation-152306) connected to **Hassio using Homematic CCU Addon 9.6**

The window sensor works like a charm. The thermostats are shown in Hassio as entities but when i try to adjust temperature i get the "`Unreach: True`" message in homematic manager and therefore can not control anything. Time by time the current temperature gets updated, so there must be a connection but its not stable.

I **had** the **eTRV-B working before** but when i added the etrv-2 and the window sensor everything got screwed up after i reset the configuration.

That is the latest **Addon Output**:

_2020-01-21 01:24:24,385 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Eventlistener Handler utilization: 0/50 used
Jan 21, 2020 1:24:49 AM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy24.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:272)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:155)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Jan 21, 2020 1:24:49 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy24.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:272)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:155)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-21 01:29:24,384 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: 0 Accesspoints in Queue
2020-01-21 01:29:24,385 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used
2020-01-21 01:29:24,386 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Eventlistener Handler utilization: 0/50 used
2020-01-21 01:29:26,227 [INFO] AccessPointWatchdog - SYSTEM: Access Point Watchdog running periodic connection check...
Jan 21, 2020 1:31:34 AM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy24.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:272)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:155)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Jan 21, 2020 1:31:34 AM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy24.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:272)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:155)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:106)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-01-21 01:34:24,384 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: 0 Accesspoints in Queue
2020-01-21 01:34:24,385 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used
2020-01-21 01:34:24,385 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Eventlistener Handler utilization: 0/50 used_

And this is a screenshot of **Homematic Manager v 2.6.2** at that time:
![Unbenannt](https://user-images.githubusercontent.com/8942784/72765734-370bd900-3bee-11ea-9445-8bf52dd72d9a.JPG)

**Comment by biejay** [comment]
**Update:**

Figured out that the connection **interrupts, when i turn on my tower pc**. That sounds super strange but i were able to reproduce. The HmIP frequency normally is **868Mhz** which should not get interrupted by anything. But when i put the Pi close to the PC both thermostats get disconnected whereas when i put it away from my pc more towards one of the thermostats, this one stays connected.

I have the pc and my monitors connected via a smart socket. The problem only occurs if i start the pc, not when just the power is on.

Anyone experienced the same?
