### ISSUE TITLE
500 Internal Server Error during Google Assistant SDK setup

### ISSUE THREAD

**Issue by jacobmrhodes** [home-assistant/hassio-addons#1056]
I followed the instructions to set up the Google Assistant SDK addon in Hassio. Once I finally open the Web UI, i am promped to authenticate. I sign into Google and receive a token. I copy this token into the http://hassio.local:9324/ url and it immediately crashes with the below exception:

`500 Internal Server Error
The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/hassio_oauth.py", line 46, in token
    self.oauth2.fetch_token(self.user_data['token_uri'], client_secret=self.user_data['client_secret'], code=token)
  File "/usr/local/lib/python3.6/dist-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request`

If I try to restart the Google Assistant SDK, I just receive a 'This site cannot be reached' error. I have to uninstall the addon and reinstall it in order to attempt to reauthenticate (but the error happens again).

Below is the logs from the addon page:

`[Info] Install/Update service client_secrets file
[Info] Start WebUI for handling oauth2
[07/Feb/2020:08:49:41] ENGINE Listening for SIGTERM.
[07/Feb/2020:08:49:41] ENGINE Listening for SIGHUP.
[07/Feb/2020:08:49:41] ENGINE Listening for SIGUSR1.
[07/Feb/2020:08:49:41] ENGINE Bus STARTING
CherryPy Checker:
The Application mounted at '' has an empty config.
[07/Feb/2020:08:49:41] ENGINE Started monitor thread 'Autoreloader'.
[07/Feb/2020:08:49:41] ENGINE Serving on http://0.0.0.0:9324
[07/Feb/2020:08:49:41] ENGINE Bus STARTED
192.168.86.31 - - [07/Feb/2020:08:49:43] "GET / HTTP/1.1" 200 713 "" "Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36"
[07/Feb/2020:08:50:04] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/hassio_oauth.py", line 46, in token
    self.oauth2.fetch_token(self.user_data['token_uri'], client_secret=self.user_data['client_secret'], code=token)
  File "/usr/local/lib/python3.6/dist-packages/requests_oauthlib/oauth2_session.py", line 307, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 415, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 425, in parse_token_response
    validate_token_parameters(params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/parameters.py", line 432, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/usr/local/lib/python3.6/dist-packages/oauthlib/oauth2/rfc6749/errors.py", line 405, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
[07/Feb/2020:08:50:04] HTTP 
Request Headers:
  Remote-Addr: 192.168.86.31
  HOST: hassio.local:9324
  CONNECTION: keep-alive
  CACHE-CONTROL: max-age=0
  UPGRADE-INSECURE-REQUESTS: 1
  USER-AGENT: Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36
  ACCEPT: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
  ACCEPT-ENCODING: gzip, deflate
  ACCEPT-LANGUAGE: en-US,en;q=0.9
192.168.86.31 - - [07/Feb/2020:08:50:04] "GET /token?token=4%2FwQEvz6ZFtVNWpyC6kJDELX7zvbvvNcfGhl6yTtcWvzrnPtUcgeZZNJg HTTP/1.1" 500 2486 "" "Mozilla/5.0 (X11; CrOS x86_64 12607.82.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.123 Safari/537.36"
[07/Feb/2020:08:50:09] ENGINE SystemExit raised: shutting down HTTP server
[07/Feb/2020:08:50:09] ENGINE Bus STOPPING
[07/Feb/2020:08:50:09] ENGINE HTTP Server cherrypy._cpwsgi_server.CPWSGIServer(('0.0.0.0', 9324)) shut down
[07/Feb/2020:08:50:09] ENGINE Stopped thread 'Autoreloader'.
[07/Feb/2020:08:50:09] ENGINE Bus STOPPED
[07/Feb/2020:08:50:09] ENGINE Bus EXITING
[07/Feb/2020:08:50:09] ENGINE Bus EXITED
[07/Feb/2020:08:50:09] ENGINE Waiting for child threads to terminate...
[Info] Run Hass.io GAssisant SDK
ALSA lib pcm_hw.c:1713:(_snd_pcm_hw_open) Invalid value for card
[FATAL:audio_input_stream.cc(47)] Input device could not be opened: default`

**Comment by simonbjornes** [comment]
Me to :-(

**Comment by boyfromgermany** [comment]
+1

**Comment by KennyM86** [comment]
Having same issue !
