### ISSUE TITLE
no module named stat when launching Check Update Tool

### ISSUE THREAD

**Issue by chris669** [home-assistant/hassio-addons#1066]
hi, now in 104.3 running on Rpi3b+ HassOS 3.10 version 64bits of HA.
I try to update to 105.2. Before to launch update, I use the Check Configuration Home Assistant plug-in and have the following error:
`Log
starting version 3.2.8
[21:45:32] INFO: Don't worry, this temporary installation is not overwriting your current one.
[21:45:32] INFO: Installing Home Assistant: latest...
[21:45:32] INFO: Please be patient, this might take a few minutes...
Fatal Python error: initsite: Failed to import the site module
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site.py", line 73, in <module>
    import os
  File "/usr/local/lib/python3.7/os.py", line 27, in <module>
    import stat as st
ModuleNotFoundError: No module named 'stat'
[21:45:32] ERROR: An error occurred while installing Home Assistant:    `

**Comment by chris669** [comment]
can now install 105.3, but the Check Configuration Tool always gives the same error. So unable to check config before launching update...

**Comment by chris669** [comment]
OK, I do not care too...
