### ISSUE TITLE
New "File editor" (Configurator 4.4) UI not loading

### ISSUE THREAD

**Issue by fi-sch** [home-assistant/hassio-addons#1093]
I have a problem after updating from Configurator version 4.2 to 4.4. UI seems to not load. I tried restarting add-on, restarting HA, clearing browser cache and so on.

Here's a screen shot of that issue:
<img width="1280" alt="Zrzut ekranu 2020-02-18 o 09 50 43" src="https://user-images.githubusercontent.com/59969726/74719657-bd8af900-5234-11ea-925f-d422504bfd19.png">

**Comment by stickpin** [comment]
Hi,

Yes, same on my end.
In the logs I see the following:
```
INFO:2020-02-18 09:56:20,176:hass_configurator.configurator:Starting server
INFO:2020-02-18 09:56:20,177:hass_configurator.configurator:Listening on: http://0.0.0.0:8099
INFO:2020-02-18 09:57:05,282:hass_configurator.configurator:172.30.32.2 - "GET / HTTP/1.1" 200 -
INFO:2020-02-18 09:57:05,878:hass_configurator.configurator:172.30.32.2 - "GET /material-icons.fallback.css HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:57:05,879:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/material-icons.fallback.css'
INFO:2020-02-18 09:57:05,886:hass_configurator.configurator:172.30.32.2 - "GET /style.css HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:57:05,888:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/style.css'
INFO:2020-02-18 09:57:05,963:hass_configurator.configurator:172.30.32.2 - "GET /jquery-3.4.1.min.js HTTP/1.1" 200 -
INFO:2020-02-18 09:57:05,965:hass_configurator.configurator:172.30.32.2 - "GET /materialize.min.js HTTP/1.1" 200 -
INFO:2020-02-18 09:57:05,967:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 09:57:05,968:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/jquery-3.4.1.min.js'
CRITICAL:2020-02-18 09:57:05,971:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/js-yaml.min.js'
CRITICAL:2020-02-18 09:57:05,972:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/materialize.min.js'
```

Thanks in advance.

**Comment by frenck** [comment]
Thanks for reporting. I'll dive in immediately.

**Comment by stickpin** [comment]
@frenck 
A bit more logs:
```
----------------------------------------
Exception happened during processing of request from ('172.30.32.2', 42252)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/hass_configurator/configurator.py", line 939, in do_GET
    self.wfile.write(data)
  File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
TypeError: a bytes-like object is required, not 'NoneType'
----------------------------------------
----------------------------------------
Exception happened during processing of request from ('172.30.32.2', 42254)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/socketserver.py", line 650, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.7/socketserver.py", line 360, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/local/lib/python3.7/socketserver.py", line 720, in __init__
    self.handle()
  File "/usr/local/lib/python3.7/http/server.py", line 426, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.7/http/server.py", line 414, in handle_one_request
    method()
  File "/usr/local/lib/python3.7/site-packages/hass_configurator/configurator.py", line 889, in do_GET
    self.wfile.write(data)
  File "/usr/local/lib/python3.7/socketserver.py", line 799, in write
    self._sock.sendall(b)
CRITICAL:2020-02-18 10:07:02,020:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/materialize.min.js'
INFO:2020-02-18 10:07:02,044:hass_configurator.configurator:172.30.32.2 - "GET /js-yaml.min.js HTTP/1.1" 200 -
CRITICAL:2020-02-18 10:07:02,045:hass_configurator.configurator:[Errno 2] No such file or directory: '/usr/local/lib/python3.7/site-packages/hass_configurator/js-yaml.min.js'
```

**Comment by McGiverGim** [comment]
I can confirm the bug. Same problem as above.

**Comment by TallPaul78** [comment]
Just the same

**Comment by P-Verbrugge** [comment]
Same happend to me here. Rolled back to 4.2.

**Comment by frenck** [comment]
Version 4.5 is currently building and shows up in the add-on store any moment now.

If you don't see it yet, please reload the add-on store by clicking the refresh icon in the top right of the add-ons store.

Sorry about this 🙏

**Comment by fi-sch** [comment]
> Version 4.5 is currently building and shows up in the add-on store any moment now.
> 
> If you don't see it yet, please reload the add-on store by clicking the refresh icon in the top right of the add-ons store.
> 
> Sorry about this 🙏

Works well. Thank you :)
