### ISSUE TITLE
After updating to latest deconz 5.3.3 

### ISSUE THREAD

**Issue by markmghali** [home-assistant/hassio-addons#1355]
I have these errors in my logs and Home Assistant states Automation platform failed to configure. I reconfigured my Home assistant automations that involve deconz devices and they work fine. still have this error 
Log Details (ERROR)
Logger: homeassistant.config
Source: config.py:404
First occurred: 1:36:07 PM (6 occurrences)
Last logged: 1:36:07 PM

Invalid config for [automation]: (See /config/configuration.yaml, line 433).

Line 433 is group: !include groups.yaml and my groups.yaml is empty
and 

 Log Details (ERROR)
Logger: homeassistant.core
Source: components/deconz/device_trigger.py:418
First occurred: 1:36:18 PM (5 occurrences)
Last logged: 1:36:18 PM

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 419, in async_enable_automation
    self._async_detach_triggers = await self._async_attach_triggers(True)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 455, in _async_attach_triggers
    results = await asyncio.gather(*triggers)
  File "/usr/src/homeassistant/homeassistant/components/automation/device.py", line 31, in async_attach_trigger
    return await platform.async_attach_trigger(hass, config, action, automation_info)
  File "/usr/src/homeassistant/homeassistant/components/deconz/device_trigger.py", line 418, in async_attach_trigger
    raise InvalidDeviceAutomationConfig
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig
Connection lost. Reconnecting…

**Comment by sanderdw** [comment]
Looks a little like my problem as well, but don't really where the issue is coming from:

`Logger: homeassistant.components.websocket_api.http.connection.2787272752
Source: components/deconz/device_trigger.py:418
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:36:08 (1 occurrences)
Last logged: 21:36:08

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 130, in handle_call_service
    connection.context(msg),
  File "/usr/src/homeassistant/homeassistant/core.py", line 1253, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1288, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 518, in admin_handler
    await result
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 216, in reload_service_handler
    await _async_process_config(hass, conf, component)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 523, in _async_process_config
    await component.async_add_entities(entities)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 295, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 444, in _async_add_entity
    await entity.async_added_to_hass()
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 349, in async_added_to_hass
    await self.async_enable()
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 409, in async_enable
    self._async_detach_triggers = await self._async_attach_triggers(False)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 455, in _async_attach_triggers
    results = await asyncio.gather(*triggers)
  File "/usr/src/homeassistant/homeassistant/components/automation/device.py", line 31, in async_attach_trigger
    return await platform.async_attach_trigger(hass, config, action, automation_info)
  File "/usr/src/homeassistant/homeassistant/components/deconz/device_trigger.py", line 418, in async_attach_trigger
    raise InvalidDeviceAutomationConfig
homeassistant.components.device_automation.exceptions.InvalidDeviceAutomationConfig`

**Comment by sabellwind** [comment]
I'm also experiencing some weird behaviour since the latest update. A few of my lights have been showing a state of 'on' when they're actually off, and when turned off from Home Assistant, immediately revert back to showing 'on'. The light globes themselves were never on during this time. I went over the add-on logs and found one of the lights in question is identified as 0x0017880103433cdb. This comes up in the logs when the switch is flicked in Home Assistant.

```
10:59:48:845 0x0017880103433CDB onOff 1 --> 0
10:59:48:986 	0x0017880103433CDB force poll (2)
```

**Comment by migo-dev** [comment]
@sabellwind I had the same problem with some of my lamps (Hue LED Strip & Ikea bulbs). After upgrading to 5.3.4 (released today), it was gone.

**Comment by markmghali** [comment]
yes, it looks like it is fixed for me as well after updating to latest version 

closing this
