### ISSUE TITLE
Deconz add-on stops ~ once a week

### ISSUE THREAD

**Issue by limitless-code** [home-assistant/hassio-addons#1561]
## The problem

Deconz add-on stops ~ once or twice a week. In order to recover I click start for the deconz addon to start until the next crash in ~ 7 days.
As the add-on has stopped there are no logs in the log tab of the add-on. Only home assistant logs. Not sure which configs you require if at all, please let me know if you require configs and which configs?

Thanks!

## Environment

- Add-on with the issue: 
deconz
- Add-on release with the issue:
6.2.3 
- Last working add-on release (if known): 
6.2.1
- Operating environment (OS/Supervised): 
HASSOS
- Zigbee device
conbeeII firmware 26580700

arch | aarch64
-- | --
chassis | embedded
dev | false
docker | true
docker_version | 19.03.11
hassio | true
host_os | HassOS 4.12
installation_type | Home Assistant OS
os_name | Linux
os_version | 4.19.127-v8
python_version | 3.8.3
supervisor | 235
timezone | Europe/London
version | 0.114.4
virtualenv | false

## Problem-relevant configuration

```yaml

```

## Traceback/Error logs

```
Logger: pydeconz.websocket
Source: /usr/local/lib/python3.8/site-packages/pydeconz/websocket.py:81

2020-08-31 00:24:16 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 410, in async_trigger
    and not self._cond_func(variables)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 590, in if_action
    return all(check(hass, variables) for check in checks)
  File "/usr/src/homeassistant/homeassistant/components/automation/__init__.py", line 590, in <genexpr>
    return all(check(hass, variables) for check in checks)
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 420, in template_if
    return async_template(hass, value_template, variables)
  File "/usr/src/homeassistant/homeassistant/helpers/condition.py", line 400, in async_template
    value = value_template.async_render(variables)
  File "/usr/src/homeassistant/homeassistant/helpers/template.py", line 230, in async_render
    return compiled.render(kwargs).strip()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
    self.environment.handle_exception()
  File "/usr/local/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "/usr/local/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 1, in top-level template code
TypeError: '>' not supported between instances of 'NoneType' and 'int'
2020-08-31 23:29:43 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:30:01 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:30:20 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:30:38 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:30:56 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:31:14 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:31:32 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:31:50 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:32:08 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:32:26 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:32:44 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:33:02 ERROR (MainThread) [pydeconz.websocket] Client connection error
2020-08-31 23:33:20 ERROR (MainThread) [pydeconz.websocket] Client connection error

```

**Comment by SiliconAvatar** [comment]
Duplicate of #1546 ?

**Comment by Mimiix** [comment]
@SiliconAvatar Yep!

**Comment by limitless-code** [comment]
Duplicate of #1546. Closing, thanks!
