### ISSUE TITLE
Motioneye 0.10.0 , motion fails to start error, no camera feed anymore

### ISSUE THREAD

**Issue by pergolafabio** [home-assistant/hassio-addons#1592]
## The problem
Hi,

just updated my addon to 0.10.0 , i use it only for 1 local attached USB camera, but it doesnt worj anymore, no more feed

## Environment

- Add-on with the issue: 0.10.0
- Last working add-on release (if known):  0.9.0
- Operating environment (OS/Supervised):  HassOS

## Traceback/Error logs

```
WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
 WARNING: Connect error on fd 14: ECONNREFUSED
[23/Sep/2020:22:40:23 +0200] 200 -(192.168.0.232) GET /picture/1/current/?_=1600893618411&_username=admin&_signature=cdca49ff4fe8af2a241afde955e056cfdb488633 HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36)
 WARNING: Connect error on fd 14: ECONNREFUSED
[23/Sep/2020:22:40:23 +0200] 200 -(192.168.0.232) GET /picture/2/current/?_=1600893618411&_username=admin&_signature=4844726a6a1ee0e32e6b49c15828dcd7990577ee HTTP/1.1 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36)
 WARNING: Connect error on fd 13: ECONNREFUSED
   ERROR: motion not running, starting it
   ERROR: failed to start motion: motion failed to start
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
    motionctl.start()
  File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 129, in start
    raise Exception('motion failed to start')
Exception: motion failed to start
   ERROR: motion not running, starting it
   ERROR: failed to start motion: motion failed to start
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/motioneye/server.py", line 325, in checker
    motionctl.start()
  File "/usr/lib/python2.7/site-packages/motioneye/motionctl.py", line 129, in start
    raise Exception('motion failed to start')
Exception: motion failed to start
   ERROR: motion not running, starting it
   ERROR: failed to start motion: motion failed to start

```

**Comment by frenck** [comment]
Update to v0.10.1
