### ISSUE TITLE
Connect with DuckDNS.org, although the add-on is deinstalled

### ISSUE THREAD

**Issue by slofii** [home-assistant/hassio-addons#1632]
## The problem

I can connect to my Home Assistant with duckdns although I deleted the Add-on. 

## Environment

- Home Assistant Core release with the issue: 116.4
- Last working Home Assistant Core release (if known): unknown
- Operating environment (OS/Container/Supervised/Core): HassOS 4.14
- Integration causing this issue: DuckDNS
- Link to integration documentation on our website: https://www.home-assistant.io/integrations/duckdns/

## Problem-relevant `configuration.yaml`

```homeassistant:
  name: HA_Daheim
  latitude: xxxxxx
  longitude: xxxxxxxx
  elevation: xxx
  unit_system: metric
  time_zone: Europe/Berlin
#  packages: !include_dir_named include
  allowlist_external_dirs:
    - /config/
  customize: !include customize.yaml
#  external_url: "https://xxxx.duckdns.org"
  internal_url: "http://192.168.178.125:8123"

```

## Traceback/Error logs

```2020-10-20 13:41:27 ERROR (MainThread) [homeassistant.components.cert_expiry] Error fetching xxx.duckdns.org:8123 data: Connection refused by server: slofi.duckdns.org:8123
2020-10-20 13:41:27 WARNING (MainThread) [homeassistant.config_entries] Config entry for cert_expiry not ready yet. Retrying in 5 seconds
2020-10-20 13:41:43 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection.1803437920] Error handling message: Unknown error
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/connection.py", line 95, in async_handle
    handler(self.hass, self, schema(msg))
  File "/config/custom_components/browser_mod/connection.py", line 36, in handle_update
    devices[deviceID].update(msg.get("data", None))
  File "/config/custom_components/browser_mod/connection.py", line 72, in update
    self.sensor = self.sensor or create_entity(
  File "/config/custom_components/browser_mod/helpers.py", line 30, in create_entity
    adder = hass.data[DOMAIN][DATA_ADDERS][platform]
KeyError: 'sensor'
2020-10-20 13:41:47 ERROR (MainThread) [pyhaversion] Timeout error fetching version information from Hassio,
2020-10-20 13:42:00 ERROR (SyncWorker_21) [homeassistant.components.zeroconf] Home Assistant instance with identical name present in the local network
```

## Additional information

I opened an other issue about HomeKit, which I can't connect. Maybe the issues are connected.

**Comment by frenck** [comment]
The DuckDNS add-on updates the DNS records in your DuckDNS account. Removing the add-on, does not remove your DuckDNS account. It simply stops updating your DNS record.

However, it might still be a valid record (until the IP address of your internet connection changes).

So, is that the case maybe?

**Comment by slofii** [comment]
Oh boy, seems im an idiot... 
Thats the case, I didn't knew this and thought its enough to delete the add-on. Thanks so much!

But then its not the reason for my main problem. I can't connect HomeKit but it shows me every time, that HA discovered a HomeKit bridge. And in the logs it found a identical case. Im desperated and didn't knew, what I could do. 
Maybe, someone can help me with this issue too?
https://github.com/home-assistant/core/issues/41874

**Comment by frenck** [comment]
That case will be handled in the other issues and is not related to this one.

I'll close this one up as per your answer looks complete for this issue.
