### ISSUE TITLE
Hassio: Mosquitto MQTT server won't start

### ISSUE THREAD

**Issue by Cabalist** [home-assistant/hassio-addons#261]
**Home Assistant release (`hass --version`):**
Hassio 0.64.1

**Python release (`python3 --version`):**
N/A for Hassio

**Component/platform:**
 Mosquitto broker installed from Hassio add-ons

**Description of problem:**
MQTT server doesn't start when the start button is clicked on this page:
http://hassio.local:8123/hassio/addon/core_mosquitto

Does not start with the system either.

This worked with <0.64.1 .    No configuration changes prior.
**Expected:**

MQTT server running

**Problem-relevant `configuration.yaml` entries and steps to reproduce:**

1. Try and start Mosquitto server from the web interface by clicking start
2. It appears to start but reloading the page shows that the MQTT server is not actually running.
3. 

Restarts and uninstalling the addon and reinstalling do not help.

**Traceback (if applicable):**
```bash

2018-02-28 23:15:14 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/aiohttp/web_protocol.py", line 416, in start
    resp = yield from self._request_handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web.py", line 325, in _handle
    resp = yield from handler(request)
  File "/usr/lib/python3.6/site-packages/aiohttp/web_middlewares.py", line 93, in impl
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/static.py", line 70, in staticresource_middleware
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/real_ip.py", line 28, in real_ip_middleware
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/ban.py", line 70, in ban_middleware
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/auth.py", line 53, in auth_middleware
    return (yield from handler(request))
  File "/usr/lib/python3.6/site-packages/homeassistant/components/http/__init__.py", line 409, in handle
    result = yield from result
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hassio/http.py", line 66, in _handle
    return _create_response_log(client, data)
  File "/usr/lib/python3.6/site-packages/homeassistant/components/hassio/http.py", line 120, in _create_response_log
    log = re.sub(r"\x1b(\[.*?[@-~]|\].*?(\x07|\x1b\\))", "", data.decode())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 138: invalid start byte

```

**Additional info:**

**Comment by Cabalist** [comment]
Issue remains with Hassio 0.64.3

**Comment by Cabalist** [comment]
I resolved this by formatting my sd card and starting over.  It may have been corruption...
