### ISSUE TITLE
HASS Configurator doesn't start after update to las version

### ISSUE THREAD

**Issue by ezar** [home-assistant/hassio-addons#365]
This is the error:

```
Traceback (most recent call last):
  File "/configurator.py", line 4841, in <module>
    main(sys.argv[1:])
  File "/configurator.py", line 4831, in main
    server_side=True)
  File "/usr/local/lib/python3.6/ssl.py", line 1149, in wrap_socket
    ciphers=ciphers)
  File "/usr/local/lib/python3.6/ssl.py", line 747, in __init__
    self._context.load_cert_chain(certfile, keyfile)
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by gabrielboliveira** [comment]
Looks like it's not able to load the SSL certificate files. I had the same issue, but when changed ssl to false, it started.

**Comment by ezar** [comment]
works!

**Comment by gabrielboliveira** [comment]
@ezar that's only a temporary fix. I've already sent a PR fixing the problem, since we shouldn't need to add the `ssl` folder to the path.
