### ISSUE TITLE
SSL handshake failed - SSLV3_ALERT_CERTIFICATE_UNKNOWN

### ISSUE THREAD

**Issue by nitobuendia** [home-assistant/hassio-addons#668]
**DuckDNS release with the issue:**
Version 1.9

**Operating environment (Hass.io/Docker/Windows/etc.):**
Version: 0.97.2
System: HassOS 2.12
Hass.io on Raspberry Pi

**Description of problem:**
Continuously getting this error on the logs:

```
Error doing job: SSL handshake failed
Traceback (most recent call last):
  File "uvloop/sslproto.pyx", line 500, in uvloop.loop.SSLProtocol._on_handshake_complete
  File "uvloop/sslproto.pyx", line 484, in uvloop.loop.SSLProtocol._do_handshake
  File "/usr/local/lib/python3.7/ssl.py", line 774, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: SSLV3_ALERT_CERTIFICATE_UNKNOWN] sslv3 alert certificate unknown (_ssl.c:1076)
```

I can't confirm, but the issue seems to be related to issues with refreshing the certificate.

**Problem-relevant `configuration.yaml` entries and (fill out even if it seems unimportant):**
DuckDNS set up:
```js
{
  "lets_encrypt": {
    "accept_terms": true,
    "certfile": "fullchain.pem",
    "keyfile": "privkey.pem"
  },
  "token": "<my-token>",
  "domains": [
    "<my-domain>.duckdns.org"
  ],
  "seconds": 300
}
```

**Additional information:**
This started appearing recently, with no changes on my http, DuckDNS or equivalent component/addon.

I have seen other related issues on HomeAssistant and I've added them to [my issue report](https://github.com/home-assistant/home-assistant/issues/26178) there. I also see similar issues on this componenet like #409 or #271 but both are closed.

I tried uninstalling the addon and reinstalling it, and also removing the certificates. The certificates got recreated and said they are valid until October 2019, but the error persists.

This produces a large number of logs per minute, which is annoying and not sure of the impact of performance on the system.

**Comment by nitobuendia** [comment]
Error seems to have disappeared for the last few days. Unclear what made it appear and disappear, but closing for now.
