### ISSUE TITLE
Hass.io 99.2 + Lets Encrypt 4.0 | Spelling mistake?

### ISSUE THREAD

**Issue by Tuncay-Ayhan** [home-assistant/hassio-addons#711]
Hi,

The Let's Encrypt addon doesn't want start after updating to 4.0 . 

Here is a little system info.

**System Health**
-	arch				x86_64
-	dev					false
-	docker				true
-	hassio				true
-	os_name				Linux
-	python_version		3.7.4
-	timezone			Europe/Amsterdam
-	version				0.99.2
-	virtualenv			false

**Lovelace**
- 	mode			yaml
- 	resources		        18
- 	views			12

<details>
  <summary>My thought is that there is a spelling mistake or some kind. Also it doesn't seem to like my previous working config because the addon doesn't start(click to expand)</summary>

**ERROR**
<br>
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/hassio/hassio/addons/validate.py", line 337, in validate
    options[key] = _single_validate(coresys, typ, value, key)
  File "/usr/src/hassio/hassio/addons/validate.py", line 388, in _single_validate
    elif typ.strartswith(V_LIST):
AttributeError: 'str' object has no attribute 'strartswith'
19-09-25 00:11:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 277, in options
    body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
  File "/usr/src/hassio/hassio/api/utils.py", line 99, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/hassio/hassio/addons/validate.py", line 337, in validate
    options[key] = _single_validate(coresys, typ, value, key)
  File "/usr/src/hassio/hassio/addons/validate.py", line 388, in _single_validate
    elif typ.strartswith(V_LIST):
AttributeError: 'str' object has no attribute 'strartswith'
19-09-25 00:11:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 277, in options
    body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
  File "/usr/src/hassio/hassio/api/utils.py", line 99, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/hassio/hassio/addons/validate.py", line 337, in validate
    options[key] = _single_validate(coresys, typ, value, key)
  File "/usr/src/hassio/hassio/addons/validate.py", line 388, in _single_validate
    elif typ.strartswith(V_LIST):
AttributeError: 'str' object has no attribute 'strartswith'
</details>

**Comment by jfette** [comment]
Some more color to the issue. **strartswith**

`9-09-25 01:32:01 INFO (MainThread) [hassio.updater] Fetch update data from https://version.home-assistant.io/stable.json
19-09-25 01:33:20 INFO (SyncWorker_16) [hassio.docker.interface] Update image homeassistant/armv7-addon-ssh:6.0 to homeassistant/armv7-addon-ssh:6.4
19-09-25 01:33:20 INFO (SyncWorker_16) [hassio.docker.interface] Pull image homeassistant/armv7-addon-ssh tag 6.4.
19-09-25 01:34:04 INFO (SyncWorker_16) [hassio.docker.interface] Stop addon_core_ssh application
19-09-25 01:34:05 INFO (SyncWorker_16) [hassio.docker.interface] Clean addon_core_ssh application
19-09-25 01:34:05 INFO (SyncWorker_15) [hassio.docker.interface] Cleanup images: ['homeassistant/armv7-addon-ssh:6.0', 'homeassistant/armv7-addon-ssh:latest']
19-09-25 01:34:06 INFO (MainThread) [hassio.addons] Add-on 'core_ssh' successfully updated
19-09-25 01:34:09 INFO (SyncWorker_14) [hassio.docker.addon] Start Docker add-on homeassistant/armv7-addon-ssh with version 6.4
19-09-25 01:37:11 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/api/addons.py", line 277, in options
    body = await api_validate(addon_schema, request, origin=[ATTR_OPTIONS])
  File "/usr/src/hassio/hassio/api/utils.py", line 99, in api_validate
    data_validated = schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 594, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 386, in validate_mapping
    cval = cvalue(key_path, value)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 250, in _exec
    return func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/hassio/hassio/addons/validate.py", line 337, in validate
    options[key] = _single_validate(coresys, typ, value, key)
  File "/usr/src/hassio/hassio/addons/validate.py", line 388, in _single_validate
    elif typ.strartswith(V_LIST):
AttributeError: 'str' object has no attribute 'strartswith'
19-09-25 01:37:23 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/hassio/hassio/api/security.py", line 147, in token_validation
    return await handler(request)
  File "/usr/src/hassio/hassio/api/utils.py", line 39, in wrap_api
    answer = await method(api, *args, **kwargs)
  File "/usr/src/hassio/hassio/addons/addon.py", line 473, in start
    await self.write_options()
  File "/usr/src/hassio/hassio/addons/addon.py", line 357, in write_options
    options = schema(options)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 205, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/validators.py", line 285, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.7/site-packages/voluptuous/schema_builder.py", line 817, in validate_callable
    return schema(data)
  File "/usr/src/hassio/hassio/addons/validate.py", line 337, in validate
    options[key] = _single_validate(coresys, typ, value, key)
  File "/usr/src/hassio/hassio/addons/validate.py", line 388, in _single_validate
    elif typ.strartswith(V_LIST):
AttributeError: 'str' object has no attribute 'strartswith'`
