### ISSUE TITLE
HomeMatic CCU

### ISSUE THREAD

**Issue by Nokius** [home-assistant/hassio-addons#882]
my setup of a rpi 4 (1GB) with a HmIP-RFUSB and HM-MOD-RPI-PCB fails to connect to HmIP devices.

my rpi runs Ad don it's enabled configured, to add the devices I use homematic manager.
the manager is able to see the rf and HmIP interface.

I tried to add via SGTIN/KEY as well as with Key-Server both did not turn out well.

Anyone has a clue what I could do wrong?

this is what I see in the addon logs
```
Dec 12, 2019 11:19:10 PM io.vertx.core.eventbus.impl.HandlerRegistration
SEVERE: Failed to handleMessage
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy15.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:261)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:144)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:95)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Dec 12, 2019 11:19:10 PM io.vertx.core.impl.ContextImpl
SEVERE: Unhandled exception
de.eq3.cbcs.legacy.communication.rpc.RpcRemoteException: Error requesting method event: <class 'KeyError'>:'CENTRAL:0' Code: 1
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRpcParser.parseMethodResponse(XmlRpcParser.java:156)
	at de.eq3.cbcs.legacy.communication.rpc.internal.format.xml.XmlRequestResponseProcessor.parseResponse(XmlRequestResponseProcessor.java:171)
	at de.eq3.cbcs.legacy.communication.rpc.internal.transport.http.HttpTransport.sendRequest(HttpTransport.java:107)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.sendRequest(RpcClient.java:94)
	at de.eq3.cbcs.legacy.communication.rpc.internal.rpc.RpcClient.invoke(RpcClient.java:82)
	at com.sun.proxy.$Proxy15.event(Unknown Source)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendClient.event(LegacyBackendClient.java:123)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleReceivedStatusData(LegacyBackendNotificationHandler.java:261)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handleBackendNotification(LegacyBackendNotificationHandler.java:144)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:95)
	at de.eq3.cbcs.legacy.bidcos.rpc.internal.LegacyBackendNotificationHandler.handle(LegacyBackendNotificationHandler.java:39)
	at io.vertx.core.eventbus.impl.HandlerRegistration.deliver(HandlerRegistration.java:212)
	at io.vertx.core.eventbus.impl.HandlerRegistration.handle(HandlerRegistration.java:191)
	at io.vertx.core.eventbus.impl.EventBusImpl.lambda$deliverToHandler$3(EventBusImpl.java:505)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.TaskQueue.lambda$new$0(TaskQueue.java:60)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2019/12/12 23:19:11.133  RX SERIAL: fd 00 26 01 78 05 00 00 23 01 00 8f 12 b6 4a f0 
2019/12/12 23:19:11.135  RX SERIAL: 00 01 40 aa 6a 3d 7a 3f ae d5 8e 00 01 00 00 01 
2019/12/12 23:19:11.136  RX SERIAL: 54 01 02 0c 04 00 11 01 11 07 64 
2019/12/12 23:19:11.136  RX FRAME: 01 78 05 00 00 23 01 00 8f 12 b6 4a f0 00 01 40 aa 6a 3d 7a 3f ae d5 8e 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 
2019/12/12 23:19:11.137 <Error> CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
2019/12/12 23:19:11.138  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Message size=38
2019/12/12 23:19:11.139  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Response: 01 78 05 00 00 23 01 00 8f 12 b6 4a f0 00 01 40 aa 6a 3d 7a 3f ae d5 8e 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 .
2019/12/12 23:19:11.139 <Debug> (QEQ0412416) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2019/12/12 23:19:19.451  RX SERIAL: fd 00 26 01 79 05 00 00 26 01 00 8f 1e 83 20 f0 
2019/12/12 23:19:19.452  RX SERIAL: 00 01 40 b5 4f 8d b7 8e 61 d3 de 00 01 00 00 01 
2019/12/12 23:19:19.454  RX SERIAL: 54 01 02 0c 04 00 11 01 11 29 41 
2019/12/12 23:19:19.454  RX FRAME: 01 79 05 00 00 26 01 00 8f 1e 83 20 f0 00 01 40 b5 4f 8d b7 8e 61 d3 de 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 
2019/12/12 23:19:19.454 <Error> CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
2019/12/12 23:19:19.454  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Message size=38
2019/12/12 23:19:19.454  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Response: 01 79 05 00 00 26 01 00 8f 1e 83 20 f0 00 01 40 b5 4f 8d b7 8e 61 d3 de 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 .
2019/12/12 23:19:19.454 <Debug> (QEQ0412416) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2019/12/12 23:19:21.276  RX SERIAL: fd 00 26 01 7a 05 00 00 21 01 00 8f 12 b6 4a f0 
2019/12/12 23:19:21.278  RX SERIAL: 00 01 40 e6 d9 d8 1d 89 48 55 7d 00 01 00 00 01 
2019/12/12 23:19:21.279  RX SERIAL: 54 01 02 0c 04 00 11 01 11 e2 f7 
2019/12/12 23:19:21.279  RX FRAME: 01 7a 05 00 00 21 01 00 8f 12 b6 4a f0 00 01 40 e6 d9 d8 1d 89 48 55 7d 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 
2019/12/12 23:19:21.279 <Error> CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
2019/12/12 23:19:21.279  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Message size=38
2019/12/12 23:19:21.279  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Response: 01 7a 05 00 00 21 01 00 8f 12 b6 4a f0 00 01 40 e6 d9 d8 1d 89 48 55 7d 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 .
2019/12/12 23:19:21.279 <Debug> (QEQ0412416) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2019/12/12 23:19:25.810 <Debug> Event: CENTRAL.PONG="hmm"
2019/12/12 23:19:25.810 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2019/12/12 23:19:25.810 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2019/12/12 23:19:25.810 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2019/12/12 23:19:25.811 <Debug> HSSXmlRpcEventDispatcher::Handle send 1 events
2019/12/12 23:19:25.812 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2019/12/12 23:19:25.816 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2019/12/12 23:19:25.817 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2019/12/12 23:19:25.822 <Debug> HSSXmlRpcEventDispatcher::Handle send completed
2019/12/12 23:19:29.450  RX SERIAL: fd 00 26 01 7b 05 00 00 26 01 00 8f 1e 83 20 f0 
2019/12/12 23:19:29.451  RX SERIAL: 00 01 40 6a f7 f0 36 02 b3 ae 5c 00 01 00 00 01 
2019/12/12 23:19:29.453  RX SERIAL: 54 01 02 0c 04 00 11 01 11 86 c7 
2019/12/12 23:19:29.453  RX FRAME: 01 7b 05 00 00 26 01 00 8f 1e 83 20 f0 00 01 40 6a f7 f0 36 02 b3 ae 5c 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 
2019/12/12 23:19:29.453 <Error> CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
2019/12/12 23:19:29.453  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Message size=38
2019/12/12 23:19:29.453  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Response: 01 7b 05 00 00 26 01 00 8f 1e 83 20 f0 00 01 40 6a f7 f0 36 02 b3 ae 5c 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 .
2019/12/12 23:19:29.453 <Debug> (QEQ0412416) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2019/12/12 23:19:31.412  RX SERIAL: fd 00 26 01 7c 05 00 00 22 01 00 8f 12 b6 4a f0 
2019/12/12 23:19:31.414  RX SERIAL: 00 01 40 eb e6 31 ea 4e cd 23 35 00 01 00 00 01 
2019/12/12 23:19:31.415  RX SERIAL: 54 01 02 0c 04 00 11 01 11 22 4f 
2019/12/12 23:19:31.415  RX FRAME: 01 7c 05 00 00 22 01 00 8f 12 b6 4a f0 00 01 40 eb e6 31 ea 4e cd 23 35 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 
2019/12/12 23:19:31.415 <Error> CCU2CoprocessorCommand::parseBidcosCommandResponse(): BidCoS event-message size not in specified limits. Incoming message dropped.
2019/12/12 23:19:31.415  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Message size=38
2019/12/12 23:19:31.415  CCU2CoprocessorCommand::parseBidcosCommandResponse(): Response: 01 7c 05 00 00 22 01 00 8f 12 b6 4a f0 00 01 40 eb e6 31 ea 4e cd 23 35 00 01 00 00 01 54 01 02 0c 04 00 11 01 11 .
2019/12/12 23:19:31.415 <Debug> (QEQ0412416) CCU2CommController::handleIncomingSerialFrame(): Command not parseable.
2019-12-12 23:19:34,532 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: 0 Accesspoints in Queue
2019-12-12 23:19:34,532 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Permanent-/Burstlistener Handler utilization: 0/50 used
2019-12-12 23:19:34,533 [INFO] DeviceBackgroundUpdateSubsystem - SYSTEM: Eventlistener Handler utilization: 0/50 used
2019-12-12 23:19:35,107 [INFO] AccessPointWatchdog - SYSTEM: Access Point Watchdog running periodic connection check...
2019-12-12 23:19:36,088 [INFO] TransactionManager - Transaction State: true | Size: 1
```

Thanks in advance

**Comment by pvizeli** [comment]
I had also an issue like this and at the end it was a bad solded pin. I have the same env like you running with the latest version of the add-on.

**Comment by Nokius** [comment]
@pvizeli thanks for you feed back going to verify it asap :hugs:

**Comment by Nokius** [comment]
After a chat with @pvizeli, verifying the soldering, and just using the HmIP USB dongle. I was able to connect the HmIP devices via the HmIP webUI. (which didn't work for me before addon release 9.3)

Thanks for the help!

**Comment by Nokius** [comment]
just a little update.

all my devices are added and I see no issues currently. May it was just the soldering :man_shrugging:
